name: Detour
version: 1.2.6
author: AlphaCH1337 
main: ru.alphach1337.detour.Main
commands:
    detour:
      start:
        description: Начинает обход
        usage: /start
      stop:
        description: Заканчивает обход
        usage: /stop
      join:
        description: Присоединиться к обходу
        usage: /join
      next:
        descrption: Следующий игрок
        usage: /next
      usage: /detour [start, stop, join, next]